# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-monads/all/dry-monads.rbi
#
# dry-monads-1.1.0
module Dry
end
module Dry::Monads
  def self.Result(error, **options); end
  def self.included(base); end
  extend Dry::Monads::Maybe::Mixin::Constructors
  extend Dry::Monads::Result::Mixin::Constructors
  extend Dry::Monads::Task::Mixin::Constructors
  extend Dry::Monads::Try::Mixin::Constructors
  extend Dry::Monads::Validated::Mixin::Constructors
end
module Dry::Monads::Curry
  def self.call(value); end
end
class Dry::Monads::UnwrapError < StandardError
  def initialize(ctx); end
end
class Dry::Monads::InvalidFailureTypeError < StandardError
  def initialize(failure); end
end
module Dry::Monads::RightBiased
end
module Dry::Monads::RightBiased::Right
  def ===(other); end
  def apply(val = nil); end
  def bind(*args, **kwargs); end
  def curry; end
  def destructure(*args, **kwargs); end
  def discard; end
  def fmap(*arg0); end
  def or(*arg0); end
  def or_fmap(*arg0); end
  def self.included(m); end
  def tee(*args, &block); end
  def value!; end
  def value_or(_val = nil); end
  include Dry::Core::Constants
end
module Dry::Monads::RightBiased::Left
  def apply(*arg0); end
  def bind(*arg0); end
  def discard; end
  def fmap(*arg0); end
  def or(*arg0); end
  def or_fmap(*arg0); end
  def self.trace_caller; end
  def tee(*arg0); end
  def value!; end
  def value_or(val = nil); end
end
module Dry::Monads::Transformer
  def fmap2(*args); end
  def fmap3(*args); end
end
module Dry::Monads::ConversionStubs
  def self.[](*method_names); end
end
module Dry::Monads::ConversionStubs::Methods
  def self.to_maybe; end
  def self.to_result; end
  def self.to_validated; end
  def to_maybe; end
  def to_result; end
  def to_validated; end
end
class Dry::Monads::Result
  def failure; end
  def monad; end
  def self.pure(value = nil, &block); end
  def success; end
  def to_either(*args, &block); end
  def to_monad; end
  def to_result; end
  extend Anonymous_Dry_Core_Deprecations_Tagged_5
  extend Anonymous_Module_6
  extend Anonymous_Module_7
  extend Dry::Core::Deprecations::Interface
  include Anonymous_Module_4
  include Dry::Monads::Transformer
end
module Anonymous_Module_4
  def to_maybe(*arg0); end
  def to_validated(*arg0); end
end
class Dry::Monads::Result::Success < Dry::Monads::Result
  def failure?; end
  def flip; end
  def fmap(*args, &block); end
  def initialize(value); end
  def inspect; end
  def left?(*args, &block); end
  def result(_, f); end
  def right?(*args, &block); end
  def self.to_proc; end
  def success; end
  def success?; end
  def to_maybe; end
  def to_s; end
  def to_validated; end
  include Anonymous_Dry_Equalizer_8
  include Dry::Equalizer::Methods
  include Dry::Monads::RightBiased::Right
end
module Anonymous_Dry_Equalizer_8
  def cmp?(comparator, other); end
  def hash; end
  def inspect; end
end
class Dry::Monads::Result::Failure < Dry::Monads::Result
  def ===(other); end
  def failure; end
  def failure?; end
  def flip; end
  def initialize(value, trace = nil); end
  def inspect; end
  def left(*args, &block); end
  def left?(*args, &block); end
  def or(*args); end
  def or_fmap(*args, &block); end
  def result(f, _); end
  def right?(*args, &block); end
  def self.to_proc; end
  def success?; end
  def to_maybe; end
  def to_s; end
  def to_validated; end
  def trace; end
  def value_or(val = nil); end
  include Anonymous_Dry_Equalizer_9
  include Dry::Equalizer::Methods
  include Dry::Monads::RightBiased::Left
end
module Anonymous_Dry_Equalizer_9
  def cmp?(comparator, other); end
  def hash; end
  def inspect; end
end
module Dry::Monads::Result::Mixin
  include Dry::Monads::Result::Mixin::Constructors
end
module Dry::Monads::Result::Mixin::Constructors
  def Failure(value = nil, &block); end
  def Left(*args, &block); end
  def Right(*args, &block); end
  def Success(value = nil, &block); end
  extend Anonymous_Dry_Core_Deprecations_Tagged_10
  extend Anonymous_Module_11
  extend Anonymous_Module_12
  extend Dry::Core::Deprecations::Interface
end
class Dry::Monads::Task
  def ==(other); end
  def apply(val = nil); end
  def bind(&block); end
  def compare_promises(x, y); end
  def complete?; end
  def curry(value); end
  def discard; end
  def fmap(&block); end
  def initialize(promise); end
  def inspect; end
  def monad; end
  def or(&block); end
  def or_fmap(&block); end
  def promise; end
  def self.[](executor, &block); end
  def self.new(promise = nil, &block); end
  def self.pure(value = nil, &block); end
  def then(&block); end
  def to_maybe; end
  def to_monad; end
  def to_result; end
  def to_s; end
  def value!; end
  def value_or(&block); end
  def wait(timeout = nil); end
  include Anonymous_Module_13
end
class Dry::Monads::Try
  def error?; end
  def exception; end
  def failure?; end
  def self.[](*exceptions, &block); end
  def self.lift(*args, &block); end
  def self.pure(value = nil, exceptions = nil, &block); end
  def self.run(exceptions, f); end
  def success?; end
  def to_monad; end
  def value?; end
  include Anonymous_Module_14
end
class Dry::Monads::Try::Value < Dry::Monads::Try
  def bind(*args); end
  def bind_call(*args, **kwargs); end
  def catchable; end
  def fmap(*args, &block); end
  def initialize(exceptions, value); end
  def inspect; end
  def self.to_proc; end
  def to_either(*args, &block); end
  def to_maybe; end
  def to_result; end
  def to_s; end
  extend Anonymous_Dry_Core_Deprecations_Tagged_16
  extend Dry::Core::Deprecations::Interface
  include Anonymous_Dry_Equalizer_15
  include Dry::Equalizer::Methods
  include Dry::Monads::RightBiased::Right
end
class Dry::Monads::Try::Error < Dry::Monads::Try
  def ===(other); end
  def initialize(exception); end
  def inspect; end
  def or(*args); end
  def to_either(*args, &block); end
  def to_maybe; end
  def to_result; end
  def to_s; end
  extend Anonymous_Dry_Core_Deprecations_Tagged_18
  extend Dry::Core::Deprecations::Interface
  include Anonymous_Dry_Equalizer_17
  include Dry::Equalizer::Methods
  include Dry::Monads::RightBiased::Left
end
class Dry::Monads::Validated
  def bind(*arg0); end
  def self.pure(value = nil, &block); end
  def to_monad; end
  include Anonymous_Module_19
end
class Dry::Monads::Validated::Valid < Dry::Monads::Validated
  def ===(other); end
  def alt_map(_ = nil); end
  def apply(val = nil); end
  def fmap(proc = nil, &block); end
  def initialize(value); end
  def inspect; end
  def or(_ = nil); end
  def to_maybe; end
  def to_result; end
  def to_s; end
  def value!; end
  include Anonymous_Dry_Equalizer_20
  include Dry::Equalizer::Methods
end
class Dry::Monads::Validated::Invalid < Dry::Monads::Validated
  def ===(other); end
  def alt_map(proc = nil, &block); end
  def apply(val = nil); end
  def error; end
  def fmap(_ = nil); end
  def initialize(error, trace = nil); end
  def inspect; end
  def or(proc = nil, &block); end
  def to_maybe; end
  def to_result; end
  def to_s; end
  def trace; end
  include Anonymous_Dry_Equalizer_21
  include Dry::Equalizer::Methods
end
module Anonymous_Module_14
  def to_maybe(*arg0); end
  def to_result(*arg0); end
end
module Anonymous_Dry_Equalizer_15
  def cmp?(comparator, other); end
  def hash; end
  def inspect; end
end
module Anonymous_Dry_Equalizer_17
  def cmp?(comparator, other); end
  def hash; end
  def inspect; end
end
module Dry::Monads::Try::Mixin
  def Error(error = nil, &block); end
  def Value(value = nil, exceptions = nil, &block); end
  include Dry::Monads::Try::Mixin::Constructors
end
module Dry::Monads::Try::Mixin::Constructors
  def Try(*exceptions, &f); end
end
class Dry::Monads::Maybe
  def failure?; end
  def monad; end
  def none?; end
  def self.coerce(value); end
  def self.lift(*args, &block); end
  def self.pure(value = nil, &block); end
  def self.to_proc; end
  def some?; end
  def success?; end
  def to_maybe; end
  def to_monad; end
  include Dry::Monads::Transformer
end
class Dry::Monads::Maybe::Some < Dry::Monads::Maybe
  def fmap(*args, &block); end
  def initialize(value = nil); end
  def inspect; end
  def self.to_proc; end
  def to_s; end
  include Anonymous_Dry_Equalizer_22
  include Dry::Equalizer::Methods
  include Dry::Monads::RightBiased::Right
end
module Anonymous_Dry_Equalizer_22
  def cmp?(comparator, other); end
  def hash; end
  def inspect; end
end
class Dry::Monads::Maybe::None < Dry::Monads::Maybe
  def ==(other); end
  def eql?(other); end
  def hash; end
  def initialize(trace = nil); end
  def inspect; end
  def or(*args); end
  def or_fmap(*args, &block); end
  def self.instance; end
  def to_s; end
  def trace; end
  include Dry::Monads::RightBiased::Left
end
module Dry::Monads::Maybe::Mixin
  include Dry::Monads::Maybe::Mixin::Constructors
end
module Dry::Monads::Maybe::Mixin::Constructors
  def Maybe(value); end
  def None; end
  def Some(value = nil, &block); end
end
class Dry::Monads::Task::Promise < Concurrent::Promise
  def on_fulfill(result); end
  def on_reject(reason); end
end
module Anonymous_Module_13
  def to_maybe(*arg0); end
  def to_result(*arg0); end
end
module Dry::Monads::Task::Mixin
  def self.[](executor); end
  include Dry::Monads::Task::Mixin::Constructors
end
module Dry::Monads::Task::Mixin::Constructors
  def Task(&block); end
end
module Anonymous_Module_19
  def to_maybe(*arg0); end
  def to_result(*arg0); end
end
module Anonymous_Dry_Equalizer_20
  def cmp?(comparator, other); end
  def hash; end
  def inspect; end
end
module Anonymous_Dry_Equalizer_21
  def cmp?(comparator, other); end
  def hash; end
  def inspect; end
end
module Dry::Monads::Validated::Mixin
  include Dry::Monads::Validated::Mixin::Constructors
end
module Dry::Monads::Validated::Mixin::Constructors
  def Invalid(value = nil, &block); end
  def Valid(value = nil, &block); end
end
class Dry::Monads::List
  def +(other); end
  def apply(list = nil); end
  def bind(*args); end
  def coerce(other); end
  def empty?; end
  def filter; end
  def first; end
  def fmap(*args); end
  def fold_left(initial); end
  def fold_right(initial); end
  def foldl(initial); end
  def foldr(initial); end
  def head; end
  def initialize(value, type = nil); end
  def inspect; end
  def last; end
  def map(&block); end
  def monad; end
  def reduce(initial); end
  def reverse; end
  def select; end
  def self.[](*values); end
  def self.coerce(value, type = nil); end
  def self.pure(value = nil, type = nil, &block); end
  def size; end
  def sort; end
  def tail; end
  def to_a; end
  def to_ary; end
  def to_monad; end
  def to_s; end
  def traverse(proc = nil, &block); end
  def type; end
  def typed(type = nil); end
  def typed?; end
  def value; end
  extend Anonymous_Dry_Core_Deprecations_Tagged_23
  extend Dry::Core::Deprecations::Interface
  include Anonymous_Dry_Equalizer_24
  include Dry::Equalizer::Methods
  include Dry::Monads::Transformer
end
module Anonymous_Dry_Core_Deprecations_Tagged_23
end
module Anonymous_Dry_Equalizer_24
  def cmp?(comparator, other); end
  def hash; end
  def inspect; end
end
class Dry::Monads::List::ListBuilder
  def [](*args); end
  def coerce(value); end
  def initialize(type); end
  def pure(val = nil, &block); end
  def self.[](*arg0); end
  def type; end
end
module Dry::Monads::List::Mixin
  def List(value); end
end
module Dry::Monads::Do
  def self.coerce_to_monad(monads); end
  def self.for(*methods); end
  def self.halt(result); end
  def self.included(base); end
  def self.wrap_method(target, method_name); end
end
class Dry::Monads::Do::Halt < StandardError
  def initialize(result); end
  def result; end
end
module Dry::Monads::Do::All
  def self.included(base); end
end
class Dry::Monads::Do::All::MethodTracker < Module
  def extend_object(target); end
  def initialize(wrappers); end
  def wrap_method(target, method); end
  def wrappers; end
end
module Anonymous_Dry_Core_Deprecations_Tagged_5
end
module Anonymous_Module_6
  def const_missing(missing); end
end
module Anonymous_Module_7
  def const_missing(missing); end
end
module Anonymous_Dry_Core_Deprecations_Tagged_10
end
module Anonymous_Module_11
  def const_missing(missing); end
end
module Anonymous_Module_12
  def const_missing(missing); end
end
module Anonymous_Dry_Core_Deprecations_Tagged_16
end
module Anonymous_Dry_Core_Deprecations_Tagged_18
end
