# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/hanami-bootstrap/all/hanami-bootstrap.rbi
#
# hanami-bootstrap-0.5.0
module Hanami
end
module Hanami::Bootstrap
  def self.assets_path; end
  def self.gem_path; end
  def self.load!; end
end
