# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/hanami-webconsole/all/hanami-webconsole.rbi
#
# hanami-webconsole-0.1.0
module Hanami
end
module Hanami::Webconsole
end
