# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/hanami-fabrication/all/hanami-fabrication.rbi
#
# hanami-fabrication-0.1.0
module Hanami
end
module Hanami::Fabrication
end
module Fabrication
end
module Fabrication::Generator
end
class Fabrication::Generator::Hanami < Fabrication::Generator::Base
  def build_instance; end
  def persist; end
  def repository; end
  def self.supports?(klass); end
end
