# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/inflecto/all/inflecto.rbi
#
# inflecto-0.0.2
module Inflecto
  def self.camelize(input); end
  def self.classify(table_name); end
  def self.constantize(input); end
  def self.dasherize(input); end
  def self.demodulize(input); end
  def self.foreign_key(input); end
  def self.humanize(input); end
  def self.inflections; end
  def self.ordinalize(number); end
  def self.pluralize(word); end
  def self.singularize(word); end
  def self.tableize(input); end
  def self.underscore(input); end
end
class Inflecto::Inflections
  def clear; end
  def human(rule, replacement); end
  def humans; end
  def initialize; end
  def irregular(singular, plural); end
  def plural(rule, replacement); end
  def plurals; end
  def self.instance; end
  def singular(rule, replacement); end
  def singulars; end
  def uncountable(words); end
  def uncountables; end
end
