# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/relative_time/all/relative_time.rbi
#
# relative_time-5afd0fa658e2
module RelativeTime
  def self.in_words(date_to, date_from = nil, locale: nil); end
end
class RelativeTime::InWords
  def call(date_to, date_from); end
  def initialize(locale: nil); end
  def resolution(diff); end
  def self.setup; end
end
