# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/shotgun/all/shotgun.rbi
#
# shotgun-0.9.2
module Shotgun
  def self.after_fork!; end
  def self.after_fork(&block); end
  def self.before_fork!; end
  def self.before_fork(&block); end
  def self.enable_copy_on_write; end
  def self.new(rackup_file, &block); end
  def self.preload(files = nil); end
end
