# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/url_mount/all/url_mount.rbi
#
# url_mount-0.2.1
class UrlMount
  def callback(&blk); end
  def defaults; end
  def defaults=(arg0); end
  def host; end
  def host=(arg0); end
  def initialize(path, opts = nil, &blk); end
  def local_required_variables; end
  def local_segments; end
  def optional_variable_segments; end
  def optional_variables; end
  def options; end
  def options=(arg0); end
  def parse_local_segments; end
  def raw_path; end
  def raw_path=(arg0); end
  def required_to_generate?; end
  def required_variable_segments; end
  def required_variables; end
  def scheme; end
  def scheme=(arg0); end
  def to_s(env = nil, opts = nil); end
  def url(env = nil, opts = nil); end
  def url_mount; end
  def url_mount=(arg0); end
  def variables; end
end
class UrlMount::Ungeneratable < StandardError
end
class UrlMount::Segment
end
class UrlMount::Segment::Base
  def name; end
  def name=(arg0); end
  def optional_variable_segments; end
  def required_variable_segments; end
end
class UrlMount::Segment::Delimeter < UrlMount::Segment::Base
  def to_s(opts = nil); end
end
class UrlMount::Segment::Static < UrlMount::Segment::Base
  def initialize(name); end
  def to_s(opts = nil); end
end
class UrlMount::Segment::Variable < UrlMount::Segment::Base
  def initialize(name, options); end
  def required_variable_segments; end
  def to_s(opts = nil); end
end
class UrlMount::Segment::Conditional < UrlMount::Segment::Base
  def initialize(*args); end
  def optional_variable_segments; end
  def optional_variables; end
  def required_variables; end
  def to_s(opts = nil); end
end
class UrlMount::Segment::Conditional::UnrequiredUrlMount < UrlMount
  def required_to_generate?; end
end
