# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/xml-sitemap/all/xml-sitemap.rbi
#
# xml-sitemap-1.3.3
module XmlSitemap
  def self.index(options = nil); end
  def self.map(domain, options = nil); end
  def self.new(domain, options = nil); end
  def self.version; end
end
module XmlSitemap::RenderEngine
  def render_builder; end
  def render_nokogiri; end
  def render_string; end
end
class XmlSitemap::Item
  def changefreq; end
  def image_caption; end
  def image_geolocation; end
  def image_license; end
  def image_location; end
  def image_title; end
  def initialize(target, opts = nil); end
  def lastmod_value; end
  def priority; end
  def target; end
  def updated; end
  def validate_time; end
  def video_category; end
  def video_content_location; end
  def video_description; end
  def video_duration; end
  def video_expiration_date; end
  def video_expiration_date_value; end
  def video_family_friendly; end
  def video_gallery_location; end
  def video_live; end
  def video_platform; end
  def video_player_location; end
  def video_price; end
  def video_publication_date; end
  def video_publication_date_value; end
  def video_rating; end
  def video_requires_subscription; end
  def video_restriction; end
  def video_thumbnail_location; end
  def video_title; end
  def video_uploader; end
  def video_view_count; end
end
class XmlSitemap::Map
  def add(target, opts = nil); end
  def buffer; end
  def created_at; end
  def domain; end
  def empty?; end
  def group; end
  def index_url(offset, secure); end
  def initialize(domain, opts = nil); end
  def items; end
  def plain_index_url(secure); end
  def process_target(str); end
  def render(method = nil); end
  def render_to(path, options = nil); end
  def root; end
  def size; end
  def url(path = nil); end
  include XmlSitemap::RenderEngine
end
class XmlSitemap::Index
  def add(map, use_offsets = nil); end
  def initialize(opts = nil); end
  def maps; end
  def render; end
  def render_to(path, options = nil); end
end
